#!/bin/zsh

# Initial check
init(){
    ! command -v gxargs >/dev/null && { echo "ERROR: 'gxargs' command is not installed."; exit 1; }
}

# Function to create a directory if it doesn't exist
create_directory() {
    mkdir -p "$1"
}

# Function to distribute files to 'even' or 'odd' directory based on their names
distribute_files() {
    find . -maxdepth 1 -type f -name '*[02468].*' -print0 | gxargs -0 -I {} -P 4 mv {} even/
    find . -maxdepth 1 -type f -name '*[13579].*' -print0 | gxargs -0 -I {} -P 4 mv {} odd/
}

# Main Process
create_directory even
create_directory odd
distribute_files
exit 0