#!/bin/zsh

# initialize
echo $PWD

# directory check
if [[ $PWD =~ ".?_tmp.?" ]]; then
  echo "INFO: right directory: ${PWD}"
else
  echo "ERROR: wrong directory. a script has to be executed under _tmp dir. directory is ${PWD}"
  exit 1
fi

# argument check
if [[ $# -eq 0 ]]; then
  echo "INFO: run normal mode"
else
  if [[ $1 =~ [Yy] ]]; then
    echo "INFO: run rename digit mode"
    mode="Y"
  else
    echo "ERROR: wrong argument."
    exit 1
  fi
fi

# check and remove trash files and directories in one go
echo "INFO: check and remove trash files and directories..."
find ./ -type f \( -iregex ".*\.(url|db|text|txt|vix|rar|zip|ini)" -o -name ".DS_Store" -o -name "*..*" \) -print0 | xargs -0 rm
find ./ -type d -name "単ページ" -print0 | xargs -0 rm -r

# process
echo "INFO: start for zip"
for dir in * ; do
  echo "INFO: working: ${dir}"
  
    # rename and process files in the directory
    pushd "${dir}" >/dev/null
    # delete trash directory
    find . -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 rm -r
    # rename filename
    rename -v '
    s/[^0-9]*//;
    s/jpeg/jpg/;
    s/jpg\.jpg/jpg/;
    s/ \- p/_/;
    s/\ \[[A-Za-z0-9]*\]//;
    s/imgs\-//;
    s/\ \-\ p/_/
    ' *
    rename -c -f *
    if [[ $mode == "Y" ]]; then
      rename 's/(\d+)/sprintf("%03d", $1)/e' *
    fi 


#   # zip files
   zip -j "../${dir}.zip" * >/dev/null
   popd >/dev/null
   rm -r "${dir}"
done

# finalized
echo "INFO: finished."
exit 0