#!/bin/zsh

# initialize
echo $PWD

# directory check
if [[ $PWD =~ ".?_tmp.?" ]]; then
  echo "INFO: right directory: ${PWD}"
else
  echo "ERROR: wrong directory. a script has to be executed under _tmp dir. diretory is ${PWD}"
  exit 1
fi

# argument check
if [[ $# -eq 0 ]]; then
  echo "INFO: run normal mode"
else
  if [[ $1 =~ [Yy] ]]; then
    echo "INFO: run rename digit mode"
    mode="Y"
  else
    echo "ERROR: wrong argument."
    exit 1
  fi
fi

# check trash files
echo "INFO: check trash files..."
find -E ./ -type f -iregex ".*\.(url|db|text|txt|vix|rar|zip|ini)" -print0 | xargs -0 rm
find ./ -name ".DS_Store" -print0 | xargs -0 rm
find ./ -name "*..*" -print0 | xargs -0 rm

# check trach directories
echo "INFO: check trash directories..."
find ./ -name "単ページ" -print0 | xargs -0 rm -r

# process
echo "INFO: start for zip"
for f in *;
do
  # move to the directory
  echo "INFO: working directory: ${f}"
  cd "${f}"
  # delete folders
  find . -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 rm -r
  # rename file
  rename -v 's/[^0-9]*//' *
  rename -s 'jpeg' 'jpg' *
  rename -s 'jpg.jpg' 'jpg' *
  rename -s " - p" "_" *
  rename -v "s/\ \[[A-Za-z0-9]*\]//" *
  rename -v "s/imgs\-//" *
  rename -v "s/\ \-\ p/_/" *
  # change filename to small capital
  rename -c -f *
  # rename digit
  if [[ $mode == "Y" ]]; then
    rename 's/(\d+)/sprintf("%03d", $1)/e' *
  fi 

  # zip file
  zip -r ../"${f}.zip" * >/dev/null
  # back to the directory
  cd - >/dev/null
  # delete the directory
  rm -r "${f}"
done

# finalized
echo "INFO: finished."
exit 0