#!/bin/zsh

# Function to check if the correct number of arguments is provided
check_arguments() {
    if [ $# -ne 1 ]; then
        echo "ERROR: Need full path of directory"
        exit 1
    fi
}

# Function to initialize environment and log file
initialize_environment() {
    export LANG=ja_JP.UTF8
    local logdir=~/work/_logs

    if [ ! -e "${logdir}" ]; then
        mkdir -p "${logdir}"
    fi

    logfile="${logdir}/`basename ${1}`_$(date '+%Y%m%d_%H%M%S').csv"
    echo "INFO: Log file: ${logfile}"
}

# Function to process directory contents
process_directory() {
    local dirname=$1
    local i=0

    echo "INFO: Target directory: ${dirname}"
    cd "${dirname}" || exit

    ls -l | grep -v total | while read line; do
        i=$((i + 1))
        writer=`echo "${line}" | cut -d "[" -f2 | cut -d "]" -f1 | sed 's/／/\//g'`
	    author=`echo "${writer}" | cut -d "/" -f2`
	    writer=`echo "${writer}" | cut -d "/" -f1`
	    book=`echo "${line}" | cut -d "]" -f2 | cut -b 2-`

        if [ "${author}" != "${writer}" ]; then
            echo "${writer}"\\t"${author}"\\t"${book}" >> $logfile
        else
            echo "${writer}"\\t\\t"${book}" >> $logfile
        fi
    done
}

echo "INFO: Execution started."
check_arguments "$@"
initialize_environment "$1"
process_directory "$1"
echo "INFO: Execution completed."
exit 0