#!/bin/zsh

# Function to check if the correct number of arguments is provided
check_arguments() {
    [[ $# -ne 1 ]] && { echo "ERROR: Need full path of directory"; exit 1 }
}

# Function to initialize environment and log file
initialize_environment() {
    export LANG=ja_JP.UTF8
    local logdir=~/work/_logs
    mkdir -p "${logdir}"
    logfile="${logdir}/`basename ${1}`_$(date '+%Y%m%d_%H%M%S').csv"
    echo "INFO: Log file: ${logfile}"
}

# Function to process directory contents
process_directory() {
    local dirname=$1
    echo "INFO: Target directory: ${dirname}"
    cd "${dirname}" || exit 1

    # 現在のディレクトリ内のフォルダをループ処理
    for dir in */ ; do
        # フォルダ名からトリムする
        dir=${dir%/}
        
        # 正規表現を使用してフォルダ名を解析
        if [[ "$dir" =~ "\[(.+)\]\ (.+)" ]]; then
            author="${match[1]}"
            title="${match[2]}"
            
            # 作者と原作者を分割
            if [[ $author =~ "(.+)／(.+)" ]]; then
                author_name="${match[1]}"
                original_author="${match[2]}"
            else
                author_name="$author"
                original_author=""
            fi
            
            # TSV形式で出力
            echo "$author_name\t$original_author\t$title" >> "$logfile"
        fi
    done
    cd -
}

echo "INFO: Execution started."
check_arguments "$@"
initialize_environment "$1"
process_directory "$1"
echo "INFO: Execution completed."
exit 0