#!/bin/zsh

# Combined function to optimize renaming operations
optimize_rename_operations() {
  # Combine non-numeric character removal and number formatting
  rename -v 's/[^0-9]*//; s/(\d+)/sprintf("%03d", $1)/e' *

  # Change specific pattern in filenames
  pattern_from="_01"
  pattern_to="_02b"
  if ls *"${pattern_from}"* 1> /dev/null 2>&1; then
      echo "INFO: Changing pattern from '${pattern_from}' to '${pattern_to}' in filenames."
      rename -v "s/${pattern_from}/${pattern_to}/" *
  fi
}

# Main execution
optimize_rename_operations
exit 0