#!/bin/zsh

# Function to move files from a directory to parent directory and then remove the directory
move_files_and_remove_dir() {
    local dir=$1
    mv "${dir}"/* . 2>/dev/null || { echo "ERROR: directory: ${dir} does not exist"; exit 1; }
    rm -rf "${dir}"
}

# Main Process
move_files_and_remove_dir even
move_files_and_remove_dir odd
exit 0